begin tran

update rangeplan set sellthruremark = '2019 retail sales trueup in 20 wk23' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '885811'
update rangeplan set sellthruremark = '2019 retail sales trueup in 20 wk23' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '902385'
update rangeplan set sellthruremark = '2019 retail sales trueup in 20 wk23' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '444569'
update rangeplan set sellthruremark = 'checking with billing team why in -ve sell thru' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '483527'
update rangeplan set sellthruremark = 'date back repeat item' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '293232'
update rangeplan set sellthruremark = 'W1-3 actual sold in clearance price instead of FP' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '879851'
update rangeplan set sellthruremark = 'with 2019 true up USD1,000 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '550266'
update rangeplan set sellthruremark = 'with 2019 true up USD1,061 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '824435'
update rangeplan set sellthruremark = 'with 2019 true up USD1,138 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '644147'
update rangeplan set sellthruremark = 'with 2019 true up USD1,233 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '579167'
update rangeplan set sellthruremark = 'with 2019 true up USD1,460 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '922064'
update rangeplan set sellthruremark = 'with 2019 true up USD1,539 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '136663'
update rangeplan set sellthruremark = 'with 2019 true up USD11,532 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '835502'
update rangeplan set sellthruremark = 'with 2019 true up USD12,824 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '430241'
update rangeplan set sellthruremark = 'with 2019 true up USD182 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '321774'
update rangeplan set sellthruremark = 'with 2019 true up USD193 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '341585'
update rangeplan set sellthruremark = 'with 2019 true up USD2,150 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '575229'
update rangeplan set sellthruremark = 'with 2019 true up USD2,166 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '103257'
update rangeplan set sellthruremark = 'with 2019 true up USD2,214 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '594098'
update rangeplan set sellthruremark = 'with 2019 true up USD2,329 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '872125'
update rangeplan set sellthruremark = 'with 2019 true up USD2,406 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '517010'
update rangeplan set sellthruremark = 'with 2019 true up USD2,513 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '949727'
update rangeplan set sellthruremark = 'with 2019 true up USD2,591 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '159836'
update rangeplan set sellthruremark = 'with 2019 true up USD2,687 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '533997'
update rangeplan set sellthruremark = 'with 2019 true up USD20,940 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '645217'
update rangeplan set sellthruremark = 'with 2019 true up USD220 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '610609'
update rangeplan set sellthruremark = 'with 2019 true up USD3,063 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '636512'
update rangeplan set sellthruremark = 'with 2019 true up USD3,259 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '351685'
update rangeplan set sellthruremark = 'with 2019 true up USD3,360 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '905408'
update rangeplan set sellthruremark = 'with 2019 true up USD328 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '576225'
update rangeplan set sellthruremark = 'with 2019 true up USD330 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '307716'
update rangeplan set sellthruremark = 'with 2019 true up USD359 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '622917'
update rangeplan set sellthruremark = 'with 2019 true up USD378 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '563514'
update rangeplan set sellthruremark = 'with 2019 true up USD391 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '324101'
update rangeplan set sellthruremark = 'with 2019 true up USD4,687 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '812594'
update rangeplan set sellthruremark = 'with 2019 true up USD403 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '360769'
update rangeplan set sellthruremark = 'with 2019 true up USD429 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '607770'
update rangeplan set sellthruremark = 'with 2019 true up USD432 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '220871'
update rangeplan set sellthruremark = 'with 2019 true up USD445 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '635535'
update rangeplan set sellthruremark = 'with 2019 true up USD591 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '171445'
update rangeplan set sellthruremark = 'with 2019 true up USD602 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '525764'
update rangeplan set sellthruremark = 'with 2019 true up USD675 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '183252'
update rangeplan set sellthruremark = 'with 2019 true up USD7,204 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '253083'
update rangeplan set sellthruremark = 'with 2019 true up USD770 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '941674'
update rangeplan set sellthruremark = 'with 2019 true up USD774 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '529662'
update rangeplan set sellthruremark = 'with 2019 true up USD815 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '303802'
update rangeplan set sellthruremark = 'with 2019 true up USD878 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '346632'
update rangeplan set sellthruremark = 'with 2019 true up USD894 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '933172'
update rangeplan set sellthruremark = 'with 2019 true up USD903 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '894205'
update rangeplan set sellthruremark = 'with 2019 true up USD909 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '569281'
update rangeplan set sellthruremark = 'with 2019 true up USD968 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '447356'
update rangeplan set sellthruremark = 'with 2019 true up USD991 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '518888'
update rangeplan set sellthruremark = 'with 2019 true up USD997 in 21Wk4' from rangeplan a inner join rangeplanlatestversionid b on a.rangeplanid = b.rangeplanid and a.versionid = b.versionid and a.itemno = '803286'

commit tran

